config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :show, :update, :edit] do
    member do
      get :edit_account
      patch :update_account
      get :edit_profile
      patch :update_profile
    end
  end

  # 予約単独
  resources :reservations, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm # 予約の確認画面
    end
  end

  # 施設単独、施設に関する予約のルーティング
  resources :rooms do
    resources :reservations, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
      collection do
        post :confirm
      end
    end
  end

    # ユーザー登録ページのルーティング（signup）
    get '/signup', to: 'users#new', as: 'signup'
    post '/signup', to: 'users#create'

    # ログイン関連
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms, dependent: :destroy # ユーザーの削除で登録施設も削除
  has_many :reservations, dependent: :destroy # ユーザーの削除で、予約も削除

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, presence: true, confirmation: { message: "パスワードが一致しません" }, if: :password_required?
  validates :password_confirmation, presence: true, if: :password_required?

  # パスワードの暗号化メソッド(パスワードを暗号化して保存)
  has_secure_password
  # ActiveStorrage用
  has_one_attached :image

  private

  # パスワードが必要かを判定する
  def password_required?
    new_record? || password.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create]

  def show
    @user = current_user
  end

  def edit_account
    @user = User.find(params[:id])
  end

  def edit_profile
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id # ログイン状態にするため
      redirect_to root_path, notice: "アカウントを作成しました！"
    else
      render "new", status: :unprocessable_entity # バリデーションエラー時にエラーメッセージを表示するために記載
    end
  end

  def update_account
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "アカウント情報が更新されました！"
    else
      render "edit_account"
    end
  end

  def update_profile
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(@user), notice: "アカウント情報が更新されました！"
    else
      render "edit_profile"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#create</h1>
  <p>Find me in app/views/users/create.html.erb</p>
</div>

app/views/users/edit_account.html.erb
<%= render "shared/user_account_form" %>

app/views/users/edit_profile.html.erb
<%= render "shared/user_profile_form" %>

app/views/users/new.html.erb
<div class="flex items-center justify-center min-h-screen bg-gray-100">
  <div class="w-full max-w-md p-6 bg-white rounded-lg shadow-md">
    <h1 class="text-2xl font-bold text-center text-gray-800 mb-6">新規登録</h1>

    <%= form_with model: @user, local: true, class: "space-y-4" do |form| %>

      <!-- 名前の入力フィールド -->
      <div class="form-control">
        <div class="flex items-center">
          <%= form.label :name, "名前", class: "label w-auto" %>
          <% if @user.errors[:name].any? %>
            <p class="text-red-500 text-sm ml-2">
              <% @user.errors[:name].each do |message| %>
                <%= message %>
              <% end %>
            </p>
          <% end %>
        </div>
        <%= form.text_field :name, class: "input input-bordered w-full" %>
      </div>

      <!-- メールアドレスの入力フィールド -->
      <div class="form-control">
        <div class="flex items-center">
          <%= form.label :email, "メールアドレス", class: "label w-auto" %>
          <% if @user.errors[:email].any? %>
            <p class="text-red-500 text-sm ml-2">
              <% @user.errors[:email].each do |message| %>
                <%= message %>
              <% end %>
            </p>
          <% end %>
        </div>
        <%= form.email_field :email, class: "input input-bordered w-full" %>
      </div>

      <!-- パスワードの入力フィールド -->
      <div class="form-control">
        <div class="flex items-center">
          <%= form.label :password, "パスワード", class: "label w-auto" %>
          <% if @user.errors[:password].any? %>
            <p class="text-red-500 text-sm ml-2">
              <% @user.errors[:password].each do |message| %>
                <%= message %>
              <% end %>
            </p>
          <% end %>
        </div>
        <%= form.password_field :password, class: "input input-bordered w-full" %>
      </div>

      <!-- パスワード確認の入力フィールド -->
      <div class="form-control">
        <div class="flex items-center">
          <%= form.label :password_confirmation, "パスワード確認", class: "label w-auto" %>
          <% if @user.errors[:password_confirmation].any? %>
            <p class="text-red-500 text-sm ml-2">
                <%= @user.errors[:password_confirmation].first %>
            </p>
          <% end %>
        </div>
        <%= form.password_field :password_confirmation, class: "input input-bordered w-full" %>
      </div>

      <div>
        <%= form.submit '登録', class: "btn btn-primary w-full" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mx-auto mt-10">
  <!-- タブボタン -->
  <div class="flex justify-center border-b max-w-md mx-auto">
    <button
      class="tab-button px-4 py-2 font-semibold text-blue-500 border-b-2 border-blue-500 hover:text-blue-500"
      data-tab="account">
      アカウント
    </button>
    <button
      class="tab-button px-4 py-2 font-semibold text-gray-600 border-b-2 border-transparent hover:text-blue-500"
      data-tab="profile">
      プロフィール
    </button>
  </div>

  <!-- タブコンテンツ -->
  <div class="flex justify-center leading-loose">
    <div class="tab-content mt-5" id="account">
      <p class="mb-5"><span class="font-bold">メールアドレス:</span> <%= current_user.email %></p>
      <p class="mb-5"><span class="font-bold">パスワード:</span>  <span class="align-middle">*********</span></p>
      <div class="flex justify-center mt-10">
        <%= link_to "編集", edit_account_user_path(@user.id), class: "btn btn-sm btn-info px-3 py-2 font-medium text-center" %>
      </div>
    </div>

    <div class="tab-content mt-5 hidden" id="profile">
      <p class="mb-5 flex items-center">
        <span class="font-bold">画像アイコン:</span>
        <% if @user.image.attached? %>
          <%= image_tag @user.image.variant(resize_to_fill: [50, 50]), class: "rounded-full ml-2" %>
        <% else %>
          <%= image_tag "default-avatar.png", class: "rounded-full ml-2", size: "50x50" %>
        <% end %>
      </p>
      <p class="mb-5"><span class="font-bold">名前:</span> <%= current_user.name %></p>
      <p class="mb-5"><span class="font-bold">自己紹介:</span> <%= current_user.profile %></p>
      <div class="flex justify-center mt-10">
        <%= link_to "編集", edit_profile_user_path(@user.id), class: "btn btn-sm btn-info px-3 py-2 font-medium text-center" %>
      </div>
    </div>
  </div>
</div>